// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-f2kH_ggRsgPxFDWONlN0sf3GGA8NVjA',
    appId: '1:301118828041:web:f4122f347cb64fbd9592d8',
    messagingSenderId: '301118828041',
    projectId: 'lumio-b1831',
    authDomain: 'lumio-b1831.firebaseapp.com',
    storageBucket: 'lumio-b1831.firebasestorage.app',
    measurementId: 'G-17BYVS36NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVzUlx_fLxApIypPMghc_fW1PPt3Khnao',
    appId: '1:301118828041:android:697dc7ef09cefa769592d8',
    messagingSenderId: '301118828041',
    projectId: 'lumio-b1831',
    storageBucket: 'lumio-b1831.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATUF93iGGXducpo--n5YuTviwWCu8CPQk',
    appId: '1:301118828041:ios:e40bf41c53d326539592d8',
    messagingSenderId: '301118828041',
    projectId: 'lumio-b1831',
    storageBucket: 'lumio-b1831.firebasestorage.app',
    iosBundleId: 'com.example.lumio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATUF93iGGXducpo--n5YuTviwWCu8CPQk',
    appId: '1:301118828041:ios:e40bf41c53d326539592d8',
    messagingSenderId: '301118828041',
    projectId: 'lumio-b1831',
    storageBucket: 'lumio-b1831.firebasestorage.app',
    iosBundleId: 'com.example.lumio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-f2kH_ggRsgPxFDWONlN0sf3GGA8NVjA',
    appId: '1:301118828041:web:41fa1a12edffc4409592d8',
    messagingSenderId: '301118828041',
    projectId: 'lumio-b1831',
    authDomain: 'lumio-b1831.firebaseapp.com',
    storageBucket: 'lumio-b1831.firebasestorage.app',
    measurementId: 'G-JYWKCWS0RV',
  );
}
